### ISSUE TITLE
Publishing Assets/Config

### ISSUE THREAD

**Issue by Braunson** [antonioribeiro/countries#10]
Not sure but when running the publish command in the Readme, shows as publishing complete but nothing is published, even without specifying a tag nothing is published?

**Comment by uruloke** [comment]
Which Laravel version are you running?

**Comment by Braunson** [comment]
@uruloke 5.4, everything else works but publishing Config.

**Comment by uruloke** [comment]
@Braunson , I see what the problem is. There should be some views in the package according to the publishing part of the documentation, but there aren't any as far as I know. 

You should however be able to run `php artisan vendor:publish --provider=PragmaRX\Countries\ServiceProvider --tag=config`.

**Comment by uruloke** [comment]
Ping @antonioribeiro 
There is however an issue with `php artisan vendor:publish --provider=PragmaRX\Countries\ServiceProvider --tag=views`, because it refers to a folder which doesn't exist. This is caused the command `php artisan vendor:publish` to throw an error.

**Comment by Braunson** [comment]
@uruloke Still when running `php artisan vendor:publish --provider=PragmaRX\Countries\ServiceProvider --tag=config` nothing is created and there's no errors in Artisan, it simply says.. `Publishing complete.`

**Comment by uruloke** [comment]
@Braunson , did you add the service provider and did you look under config folder, the file should be called `countries.php`

**Comment by Braunson** [comment]
@uruloke Yep it's a service provider. I've looked and countries.php is not in config either.

**Comment by antonioribeiro** [comment]
Sorry for the delay, guys, but looks like, probably depending on your operating system, you need to publish it using `\\`:

```
php artisan vendor:publish --provider=PragmaRX\\Countries\\ServiceProvider
```

And I already removed that wrong views publish from the code and readme.

Thank you.

**Comment by antonioribeiro** [comment]
![image](https://cloud.githubusercontent.com/assets/3182864/24230853/f8bdb622-0f5f-11e7-9432-36446d3ef324.png)
