### ISSUE TITLE
Is it possible to return an array of all cities that are similar to a query

### ISSUE THREAD

**Issue by filtration** [antonioribeiro/countries#105]
For example:

Query: U

```
returns: [
    'Utah',
    //....
]
```

**Comment by antonioribeiro** [comment]
It's a Collection, you can whatever you need to filter results

![image](https://user-images.githubusercontent.com/3182864/43899735-41c482a6-9bb9-11e8-9501-a0dc7c2673fe.png)

https://laravel.com/docs/5.6/collections#method-filter
