### ISSUE TITLE
Class PragmaRX\Countries\Package\Services\Cache does not 

### ISSUE THREAD

**Issue by musikel** [antonioribeiro/countries#107]
Having issues with Cache Class
local.ERROR: Class PragmaRX\Countries\Package\Services\Cache does not exist {"exception":"[object] (ReflectionException(code: -1): Class PragmaRX\\Countries\\Package\\Services\\Cache does not exist at ....../vendor/laravel/framework/src/Illuminate/Container/Container.php:767)

**Comment by ronydebnath** [comment]
+1

**Comment by lionslair** [comment]
You just need to update the config file to this 

`        'service' => PragmaRX\Countries\Package\Services\Cache\Service::class,`

See for reference https://github.com/antonioribeiro/countries-laravel/issues/11

**Comment by ronydebnath** [comment]
Thanks @lionslair  for pointing to the right direction.
