### ISSUE TITLE
can't publish the config file and displays a "Class 'Countries' not found" when trying to use it

### ISSUE THREAD

**Issue by evrard-c** [antonioribeiro/countries#11]
I installed this interesting package and after completed Service provider and Alias i tried to use it on a form in a select input but unfortunately for me i receive an error "Class 'Countries' not found", so i tried to publish the config file, everything seemed to be right but i didn't found the countries.php in the config directory.
I don't really know if this issue comes from me or if there is some issues in the package

**Comment by divspace** [comment]
Same issue on 5.4.15; no configuration file or views are generated.

**Comment by antonioribeiro** [comment]
If you do a 

    php artisan vendor:publish

What happens?

**Comment by uruloke** [comment]
This seems related to #10 

Just made a clean Laravel 5.4.16 project and tried to install it. 
Here I only get this issue with the package 
`Can't locate path: </testing/vendor/pragmarx/countries/src/views/>`
But the config file is published, the `countries.php` is in the config directory.
