### ISSUE TITLE
Not Working on Laravel 5.8

### ISSUE THREAD

**Issue by charitablehumans** [antonioribeiro/countries#114]
Not installable on Laravel 5.8.

Error Message:

Problem 1
    - Installation request for pragmarx/countries ^0.5.9 -> satisfiable by pragmarx/countries[v0.5.9].
    - Conclusion: remove nesbot/carbon 2.14.2
    - Conclusion: don't install nesbot/carbon 2.14.2
    - pragmarx/countries v0.5.9 requires pragmarx/coollection ^0.6 -> satisfiable by pragmarx/coollection[v0.6.0, v0.6.1].
    - pragmarx/coollection v0.6.0 requires pragmarx/ia-collection >=5.5.33 -> satisfiable by pragmarx/ia-collection[dev-master, v5.5.33, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.2, v5.6.3, v5.6.33, v5.6.38, v5.6.9, v5.7.5].
    - pragmarx/coollection v0.6.1 requires pragmarx/ia-collection >=5.5.33 -> satisfiable by pragmarx/ia-collection[dev-master, v5.5.33, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.2, v5.6.3, v5.6.33, v5.6.38, v5.6.9, v5.7.5].
    - pragmarx/ia-collection v5.5.33 requires nesbot/carbon ~1.20 -> satisfiable by nesbot/carbon[1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection dev-master requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.0 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.1 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.10 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.11 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.12 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.2 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.3 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.33 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.38 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.6.9 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - pragmarx/ia-collection v5.7.5 requires nesbot/carbon ~1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - Can only install one of: nesbot/carbon[1.26.3, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.4, 2.14.2].
    - Can only install one of: nesbot/carbon[1.27.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.28.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.29.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.30.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.31.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.31.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.32.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.33.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.3, 2.14.2].
    - Can only install one of: nesbot/carbon[1.34.4, 2.14.2].
    - Can only install one of: nesbot/carbon[1.35.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.35.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.36.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.20.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.21.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.22.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.22.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.23.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.24.2, 2.14.2].
    - Can only install one of: nesbot/carbon[1.25.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.0, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.1, 2.14.2].
    - Can only install one of: nesbot/carbon[1.26.2, 2.14.2].
    - Installation request for nesbot/carbon (locked at 2.14.2) -> satisfiable by nesbot/carbon[2.14.2].

**Comment by MostafaAttia** [comment]
same here

**Comment by yovchev** [comment]
Temporary you can add to your composer require the latest satisfiable version of nestbox/carbon 1.36.2 it seems that Laravel framework is not complaining if we use older carbon but make sure you test your application in case you are using some carbon feathers that are not present on the old version. 

This works for me:

```
"require": {
  ....
  "laravel/framework": "5.8.*",
  "nesbot/carbon": "~1.22",
  "pragmarx/countries": "^0.5.9"
  ....
}
```

**Comment by lionslair** [comment]
The collection package seems to only need 1.22 


I think the antonioribeiro/ia-collection just needs to be locked to the 1.x branch and things will work. Not a countries issue I don't think.
https://github.com/antonioribeiro/ia-collection/blob/master/composer.json

**Comment by antonioribeiro** [comment]
Just upgraded antonioribeiro/ia-collection and they should be all compatible with Carbon 2.0 now.

**Comment by lionslair** [comment]
will it work with version 1 and 2?

> Just upgraded antonioribeiro/ia-collection and they should be all compatible with Carbon 2.0 now.

Will it work with version one and 2?

**Comment by antonioribeiro** [comment]
@lionslair 

> Will it work with version one and 2?

Yes 1 and 2. Tests were already passing for V1 I just made them pass for V2 too.
