### ISSUE TITLE
How to get the list of all timezones ?

### ISSUE THREAD

**Issue by invaders-xx** [antonioribeiro/countries#116]
I am wondering how to get the list of all timezones ? I tried $countries->timezones(); but got an error.

Many thanks in advance for your help.

David

PS : very helpful and powerful package, thanks ;-)

**Comment by SirFaenor** [comment]
For those interested I got it this way: `(new Countries())->all()->hydrate("timezones")->pluck("timezones")`

**Comment by Sander0542** [comment]
How can I get a list of them all? This gives a list of countries and their timezones, but not a single list.

**Comment by Sander0542** [comment]
I am using this code at the moment

```
$countries = new Countries();

$collection = $countries->all()->hydrate('timezones')->pluck("timezones");

$timezones = $collection->mapWithKeys(function($timezones) {
    $zones = [];

    foreach ($timezones as $timezone) {
        $zones[$timezone['zone_id']] = $timezone;
    }

    return $zones;
});
```
