### ISSUE TITLE
"ÆØÅ" in Norwegian cities not displaying correctly

### ISSUE THREAD

**Issue by kaizokupuffball** [antonioribeiro/countries#128]
Norwegian cities are not displayed correctly when they contain "ÆØÅ". The norwegian states are displayed correctly though, any chance of getting the cities to be displayed correctly as well?

**Comment by DanielRTRD** [comment]
Taking a quick look at the json-files it seems that there is just some missing encoding tags. Needs a PR.

**Comment by kaizokupuffball** [comment]
Yea, took a look myself, looks like that would solve it, but it kind off seems like the project owner has left the party 😂 There still is a PR for Laravel 7 support as well wich has not been reviewed yet 🤷‍♂

**Comment by Sunny-Ojo** [comment]
hi @kaizokupuffball , please how are you getting the cities in Norwegian? your response will be highly appreciated

**Comment by kaizokupuffball** [comment]
> 
> 
> hi @kaizokupuffball , please how are you getting the cities in Norwegian? your response will be highly appreciated

Ohman, this is a long time ago and i don't even have the project anymore.. But a quick look at the documentation i must have used something like this: `$countries->where('name.common', 'Norway')->first()->hydrate('cities')->cities;`

Hope it helps!
