### ISSUE TITLE
Can't add package to Laravel 7

### ISSUE THREAD

**Issue by kaizokupuffball** [antonioribeiro/countries#144]
I can't seem to add the package to Laravel 7. I'm not so good with the packages stuff, but the error that I seem to get is shown below.

`Problem 1
    - Installation request for pragmarx/countries 0.7.0 -> satisfiable by pragmarx/countries[v0.7.0].
    - Conclusion: remove symfony/var-dumper v5.0.5
    - Conclusion: don't install symfony/var-dumper v5.0.5
    - pragmarx/countries v0.7.0 requires pragmarx/coollection ^0.7 -> satisfiable by pragmarx/coollection[v0.7.0, v0.7.1].`

**Comment by georgie817** [comment]
Same thing here!

**Comment by kaizokupuffball** [comment]
> 
> 
> Same thing here!

I tried to fork, fix and do a pull request. But i think i f'ed it up somewhere since the build thingy failed.. and i don't know how to fix it.. Not so good at github stuff.. Let's hope the owner will fix it, or someone else with a little more experience to github 😂

**Comment by priyank989** [comment]
@antonioribeiro 
can we make this change ASAP. My lots of projects are waiting because of this package.

**Comment by diamondobama** [comment]
@antonioribeiro, could you please merge the [PR on ia-arr](https://github.com/antonioribeiro/ia-arr/pull/1) that fixes this issue?

**Comment by blindsz** [comment]
@antonioribeiro I'm having the same issue also. Hoping this will be fix ASAP.

**Comment by ngunyimacharia** [comment]
+1
