### ISSUE TITLE
Carbon Error

### ISSUE THREAD

**Issue by eonlab** [antonioribeiro/countries#153]
After install the package on laravel 7.10 I get this error:

Fatal error: Cannot declare class Illuminate\Support\Carbon, because the name is already in use in \vendor\kylekatarnls\laravel-carbon-2\src\Carbon.php on line 7

**Comment by hotmeteor** [comment]
@eonlab Do you have a Carbon 1.x or `kylekatarnls\laravel-carbon-2` installed? If so, remove them.

**Comment by eonlab** [comment]
Yes. That was the problem. Thank you
