### ISSUE TITLE
Wrong cca2 codes for certain countries

### ISSUE THREAD

**Issue by asivaneswaran** [antonioribeiro/countries#161]
Hi,

There are some countries with a 3 letter code for cca2. Is there any way to get them fixed?

Thanks,

**Comment by antonioribeiro** [comment]
You have to ask package managers of the related packages to get them fixed. This package is only downloading and compiling data from other packages.

**Comment by asivaneswaran** [comment]
They fixed it but it's not updated in this package? Is there an update command or something?

**Comment by antonioribeiro** [comment]
Yes, you can run

```
php update.php
```

Then commit and PR the changes.

Takes a lot of time to run, looks like stuck sometimes, but it’s not.
