### ISSUE TITLE
Missing tag in some svg files.

### ISSUE THREAD

**Issue by khamsolt** [antonioribeiro/countries#167]
HUN LCA SOM NLC GBR - The flags of these countries are missing tags `<?xml version="1.0" encoding="UTF-8"?>`  which is why a file is loaded along the `pragmarx/countries/flag/file/{cca3}.svg`. 

Should I count on fixing this error in the near future? And thanks for the awesome package.

**Comment by BorisDibrov** [comment]
Also the tag is missing for **UKR** and **WLF**.

**Comment by khamsolt** [comment]
And MKD, NLD

**Comment by antonioribeiro** [comment]
Please [read this](https://github.com/antonioribeiro/countries#updating), do the update yourself, and send us a Pull Request to update the files.

I'm closing this one for now, please open a new one if you still find problems and mark your Pull Request on it.

Thank you.
