### ISSUE TITLE
Missing cities Data 

### ISSUE THREAD

**Issue by sairum123** [antonioribeiro/countries#170]
A/c to my test some cities is missing from the data like for example Meriden city is missing,state: Connecticut,country: United States, how can i add this city is there any possibility that i can add more data in it ?

**Comment by antonioribeiro** [comment]
Please [read this](https://github.com/antonioribeiro/countries#updating), do the update yourself, and send us a Pull Request to update the files.

I'm closing this one for now, please open a new one if you still find problems and mark your Pull Request on it.

Thank you.
