### ISSUE TITLE
New administrative divisions of Morocco states

### ISSUE THREAD

**Issue by 5baddi** [antonioribeiro/countries#172]
Tried to update from the package data sources but i can't get the latest geo data of morocco states since 2015 it's only 12 states but still got the old data with 16 states.

Any help here 🙏🏼

**Comment by antonioribeiro** [comment]
Please [read this](https://github.com/antonioribeiro/countries#updating), do the update yourself, and send us a Pull Request to update the files.

I'm closing this one for now, please open a new one if you still find problems and mark your Pull Request on it.

Thank you.
