### ISSUE TITLE
where case insensitive?

### ISSUE THREAD

**Issue by rxng** [antonioribeiro/countries#176]
trying to search for countries only works when the letter casing is exact e.g. where('name.common'','Brazil');

but not in any other cases e.g. where('name.common'','brazil'); or where('name.common'','ilike','brazil');

How can we search?

**Comment by antonioribeiro** [comment]
It uses [Laravel Collections](https://laravel.com/docs/8.x/collections#introduction), if you can make `where()` case insensitive on Collections, you can probably do the same with Countries.
