### ISSUE TITLE
Getting translated version of a country common name

### ISSUE THREAD

**Issue by alariva** [antonioribeiro/countries#36]
Hi, thanks for the package, looks awesome!

I'd like to know how you'd go about for translating the country common name into another language.

Say I'd wanted to bring france (`FR`) and display `Francia` (in spanish) instead of `France`.

At this point, I thing about mapping the collection I get and perform something like applying `__($itemName)` to translate them.

Any other ideas?

**Comment by andradedev** [comment]
any help here please? @antonioribeiro

**Comment by uruloke** [comment]
You should have an array on each country called `translations`. Under here you will find all the translations available (please note this list is far from a complete list). 
`Countries::where('cca3', 'FRA')->first()->translations->spa->common`

**Comment by antonioribeiro** [comment]
As long as we have it translated, we should be able to

**Comment by alariva** [comment]
Have not tried it but looks like a good catch. Thanks!
