### ISSUE TITLE
How do I get a list of only the signs of the currencies?

### ISSUE THREAD

**Issue by pmvdbijl** [antonioribeiro/countries#37]
I'm currently working on a project where I need a dropdown with all currency signs. Unfortunately, I do not manage to show that. However, I'm able to show the ISO4217Code. Is there a solution or way to show only the signs in the dropdown? Thanks in advance.

**Comment by asahasrabuddhe** [comment]
Hello @pmbdbijl,

This is probably too late for you now but if you are still looking for a solution, give this a try

`
// List of all countries
$countries = Countries::all();

foreach($countries as $country)
{
        // For each country, get the sign of the currency.
	$currency = Countries::where('name.common', $country->name->common)->first()->currency->pluck('sign');
       // I am echoing the currency here, you may add it to an array or whatever :)
	echo $currency';
}`

**Comment by antonioribeiro** [comment]
Yeah, it should work.
