### ISSUE TITLE
Does this package require the Class Aliases for the facade?

### ISSUE THREAD

**Issue by xitude** [antonioribeiro/countries#4]
I noticed you call the package like this
`Countries::where('tld.0', '.ch')`
Do you require the Class Aliases to be added to the `app.php` aliases array?
I could not see it mentioned in the instructions.

**Comment by xitude** [comment]
I managed to access it via adding `'Countries' => PragmaRX\Countries\Facade::class` to `app.php` and in the controller using `use PragmaRX\Countries\Facade as Countries;` this allowed me to use the package.

**Comment by antonioribeiro** [comment]
Sorry, I probably forgot to add that alias to the docs, would you mind to send a PR? I'm travelling without a computer :/
