### ISSUE TITLE
Blade using

### ISSUE THREAD

**Issue by robertnicjoo** [antonioribeiro/countries#44]
Hi,

Please someone help me with using this in my application, currently i'm not confused anymore but desperate! 

here is my controller:

```php
use PragmaRX\Countries\Facade as Countries;
//.....
public function create()
    {
        $users = User::all();
        $countries = Countries::all()->pluck('name.common');
        return view('admin.addresses.create', compact('users', 'countries'));
    }
//......
```

and this is my blade code:

```php
{{Form::label('country', 'Country')}}
<select class="form-control" name="country">
  @foreach($countries as $country)
     <option value="">{{$country}}</option>
  @endforeach
</select>
```

What I want to achieve is:

1. List of countries (which i have)

2. List of states based on selected country

3. List of postal codes based on selected states

Ps: if it's possible to get countries flags very well if not, it's not important thing for me.

Thanks in advance. Hope someone can help :\

**Comment by robertnicjoo** [comment]
any help would be appreciated.

**Comment by idragon81** [comment]
I think you should be using AJAX requests for this, preloading all that info would be really slow

**Comment by robertnicjoo** [comment]
@idragon81 do you have any sample code of ajax?

**Comment by antonioribeiro** [comment]
Sorry, but this not a problem related to the package itself, you are using the package correctly as far as I can see, you just need to learn how to use Blade and/or Ajax. Please use the Laravel IRC or Slack chat to seek help.
