### ISSUE TITLE
No pluck possible on collections?

### ISSUE THREAD

**Issue by smoetje** [antonioribeiro/countries#68]
Using previous versions in other projects I commonly used :
`$countrylist = Countries::all()->pluck('name.common')->toArray();`
... in order to get a complete list of all countries for my forms.

Now using Laravel 5.5 with this latest package of pragmarx/countries () it appears above this is no longer working. The first time I tried, it gives me a list.  But when simply running it again, it gives me an empty array instead.  I can't get head or tails on it.  Nevertheless, I checked the type of the result Countries::al() and it's a collection.  So normally pluck() should do just fine?!

I have tried with using both:
use PragmaRX\Countries\Package\Countries; (which I usually used)
use PragmaRX\CountriesLaravel; (which I found in the latest changelog)

I installed the serviceprovider and tried to set cache to 'false':
` artisan vendor:publish --provider="PragmaRX\CountriesLaravel\Package\ServiceProvider"`

`
dump(Countries::all()->pluck('name.common')); // not reliably working`

Collection {#326 ▼
    #__items: []
    #allowItems: false
}

`dump(Countries::where('name.common', 'France')); // working, resulting in France`

Collection {#364 ▼
    #__items: array:1 [▶]
    #allowItems: false
    #items: []
}

`$countrylist = new Countries;
dump($countrylist->all());                       // listing full collection of 266 items
`

Collection {#374 ▼
    #__items: array:266 [▶]
    #allowItems: false
    #items: []
}

`dump($countrylist->all()->pluck('name.common')); // not working neither, returning empty array in collection
`

Collection {#355 ▼
    #__items: []
    #allowItems: false
}

In the end I got my result anyway with vanilla php just as I wanted:
`$test = $countrylist->all()->toArray();`
`$result = array_pluck($test, 'name.common');`

But in any case I'm reporting it here to take a look at it.  I'm still learning, so either I'm doing something wrong or... something is wrong?

**Comment by smoetje** [comment]
Just another test to illustrate the issue:

`dump(Countries::all()->pluck('name.common'));    // now working`
`dump(Countries::where('name.common', 'France')); // working, resulting in France`
`$countrylist = new Countries;                    // try instantiating instead`
`dump($countrylist->all());                       // listing collection of 266 items`
`dump($countrylist->all()->pluck('name.common')); // not working, returning empty array in collection`

        

        Output:
        Collection {#321 ▼
            #__items: array:266 [▶]
            #allowItems: false
        }
        Collection {#867 ▼
            #__items: array:1 [▶]
            #allowItems: false
        }
        Collection {#851 ▼
            #__items: array:266 [▶]
            #allowItems: false
            #items: []
        }
        Collection {#323 ▼
            #__items: []
            #allowItems: false
        }

        After running again/refreshing screen (F5):
        Collection {#321 ▼
            #__items: []            --> ??!
            #allowItems: false
        }
        Collection {#358 ▼
            #__items: array:1 [▶]
            #allowItems: false
            #items: []
        }
        Collection {#368 ▼
            #__items: array:266 [▶]
            #allowItems: false
            #items: []
        }
        Collection {#349 ▼
            #__items: []
            #allowItems: false
        }](url)

**Comment by antonioribeiro** [comment]
Should be fixed now. Thanks for reporting.
