### ISSUE TITLE
Error found on Laravel 5.5

### ISSUE THREAD

**Issue by ronjunelopez** [antonioribeiro/countries#74]
Hi, is there any fix for this error? I really need this library for my Laravel application. 👍 

I've _successfully_ installed the library in ubuntu 16.0 php 7.0 and laravel 5.5 and tested `Country:all()` and it returns this error `Trait 'Tightenco\Collect\Support\Traits\Macroable' not found`

**Comment by rjsworking** [comment]
It's not working on Laravel 5.6 too. Same error.

**Comment by antonioribeiro** [comment]
Unfortunatelly laravel/framwork is not letting tightenco/collect install because of:

https://github.com/laravel/framework/compare/5.6...antonioribeiro:patch-7

**Comment by ronjunelopez** [comment]
Is there any work around to make it work temporarily?

**Comment by antonioribeiro** [comment]
Should work now, I just reverted it back to use ia-collection again, so those are the versions you should see:

![image](https://user-images.githubusercontent.com/3182864/36156163-706f7610-10bd-11e8-966e-45726c83d4b4.png)

**Comment by antonioribeiro** [comment]
This is the actual PR: https://github.com/laravel/framework/pull/23147.

**Comment by rjsworking** [comment]
Thank you. It's working now.
Cheers

**Comment by antonioribeiro** [comment]
Nice! Thanks for reporting it.
