### ISSUE TITLE
Problem on the laravel 5.5

### ISSUE THREAD

**Issue by olegpy** [antonioribeiro/countries#77]
Sometimes when i do this request Countries::all()->pluck('translations.rus.common', 'postal') in my controller i see sometimes slow download page and sometimes see error about wait more 60 seconds. Help me. please

**Comment by olegpy** [comment]
i send here screenshot, which i see sometimes https://prnt.sc/ifgui7

**Comment by Cykotitan** [comment]
Having the same issue, it seems related to country cache being regenerated every 10 minutes. This duration of 10 minutes is hardcoded in file vendor/pragmarx/countries/src/package/Data/Repository.php in function call:
`return $this->cache->set($cacheKey, $result, 10);`

I had to manually change 10 to a higher number, as I was not able to change it in src/config/countries.php in the vendor package - the value doesn't seem used in this method.
I suggest something like this instead:
`return $this->cache->set($cacheKey, $result, $this->config->get('cache.duration'));`

In additional, I was not able to publish the configuration using this command
`php artisan vendor:publish --provider=PragmaRX\\Countries\\ServiceProvider`

**Comment by olegpy** [comment]
I which files you did changes as vendor:publish? Because i also can't to do this comand php artisan vendor:publish --provider=PragmaRX\\Countries\\ServiceProvider

**Comment by antonioribeiro** [comment]
Some notes:

- If you are using Laravel, you should be using the [Laravel bridge](https://github.com/antonioribeiro/countries-laravel), it uses Laravel's Cache, which is higly configurable
- When using it outside Laravel, it uses Nette\Cache, but you can easily switch to any other caching system.
- Hard coded fixed.
- Installation (of the bridge) on Laravel 5.5 fixed too.

**Comment by antonioribeiro** [comment]
Looks like it's still in the docs.

**Comment by antonioribeiro** [comment]
Docs fixed.

**Comment by antonioribeiro** [comment]
Just pushed some more changes to Countries and Coollection. Huge improvements in speed.

**Comment by Cykotitan** [comment]
Looking good, what previously took 9 seconds to generate (countries with extended info) is now instant.
