### ISSUE TITLE
Unable to publish configuration file

### ISSUE THREAD

**Issue by bilfeldt** [antonioribeiro/countries#90]
According to documentation, then it should be possible to publish the packages config file using

`php artisan vendor:publish --provider=PragmaRX\Countries\ServiceProvider `

But no configuration file is generated.

Clearing the cache with `php artisan config:clear` does not seem to fix the issue nor does `php artisan cache:clear`

I am currently testing on Laravel 5.5.

**Comment by antonioribeiro** [comment]
This repository is for the PHP agnostic version, you should install https://github.com/antonioribeiro/countries-laravel

**Comment by bilfeldt** [comment]
Sorry, that I the version I am using, I just did not see that I had posted it here.
